// <auto-generated />
namespace Jen_Nico_BoVoyage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModifPersonne : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifPersonne));
        
        string IMigrationMetadata.Id
        {
            get { return "201807100928123_ModifPersonne"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
